### ISSUE TITLE
Restrict CORVO cognitive test to one test type?

### ISSUE THREAD

**Issue by jdpigeon** [NeuroTechX/neurodoro#13]
CORVO (our cognitive test webapp) seems to be working well, but the fact that it switches to different types of tests partway through might throw off our classifier.

Based on feedback from participants, the last test with the numbers is especially easy and probably doesn't elicit the same degree of concentration.

I think we need to stick to one task for the first iteration of the classifier.

**Comment by cbattista** [comment]
Makes sense.  Should put up a separate site or have a link off the main one
that takes the user to the neurodoro experience.

**Comment by jdpigeon** [comment]
That's a good idea!

All we would need to do on the app side if you made a separate site would be to change the url in the WebView component here: https://github.com/NeuroTechX/neurodoro/blob/master/src/scenes/recorder.js
